version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.8.25-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - .rabbitmq/data/:/var/lib/rabbitmq/
      - .rabbitmq/log/:/var/log/rabbitmq/

  postgres:
    container_name: postgres
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: dev
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    restart: unless-stopped
